import type { Metadata } from "next";
import { Space_Grotesk, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Preloader } from "@/components/ui/preloader";
import { Toaster } from "sonner";
import { ConditionalLayout } from "@/components/ConditionalLayout";
import { NavbarDemo } from "@/components/navbar";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jogaad India",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${geistMono.variable} font-sans antialiased`}
        style={{ overflowX: 'hidden' }}
      >   
        <Toaster position="top-right" richColors />
        <Preloader />
        <ConditionalLayout>
          
          {children}
        </ConditionalLayout>
      </body>
    </html>
  );
}
