import type { Metadata } from "next";
import { Space_Grotesk, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Preloader } from "@/components/ui/preloader";
import { Toaster } from "sonner";
import { ConditionalLayout } from "@/components/ConditionalLayout";
import { getAuthSession } from "@/utils/auth/getAuthSession";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jogaad India",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialAuth = await getAuthSession();
  return (
    <html lang="en">
      <head>
        <script src="https://checkout.razorpay.com/v1/checkout.js" async></script>
      </head>
      <body
        className={`${spaceGrotesk.variable} ${geistMono.variable} font-sans antialiased`}
        style={{ overflowX: 'hidden' }}
      >   
        <Toaster position="top-right" richColors />
        <Preloader />
        <ConditionalLayout initialAuth={initialAuth}>
          
          {children}
        </ConditionalLayout>
      </body>
    </html>
  );
}
